############################################################
# +------------------------------------------------------+ #
# |                   MultiChat2 Spigot                  | #
# +------------------------------------------------------+ #
############################################################

##################
#   DON'T EDIT   #
version: "@version@" #
##################

# Specify the name of this server here for the %SERVER% placeholder
server_name: "UNNAMED_SERVER"

############################################################
# +------------------------------------------------------+ #
# |                        Global                        | #
# +------------------------------------------------------+ #
############################################################

global_settings:
  # Should this server use a different format for the global chat than the one assigned in the proxy plugins folder?
  # Useful if you want to use local placeholders that may only be present on one server.
  override_global: false
  # If you do not want chat messages to be sent to the proxy, you can set this to true.
  prevent_global: false
  # The format of overridden global messages.
  # Placeholders:
  # %name%        - The name of the sender (provided by Spigot)
  # %displayname% - The display name of the sender (provided by Spigot)
  # %prefix%      - The prefix of the sender (provided by Vault)
  # %suffix%      - The suffix of the sender (provided by Vault)
  # %nick%        - The nickname of the sender (provided by MultiChat2)
  # %server%      - The server of the sender (provided by the setting at the top)
  # %world%       - The world of the sender (provided by Spigot)
  # The message will be added at the end of the format.
  global_format: "&5[&dG&5] &f%displayname%&f: "

############################################################
# +------------------------------------------------------+ #
# |                        Local                         | #
# +------------------------------------------------------+ #
############################################################

local_settings:
  # Should MultiChat2 set the format of the local chat? (Leaving this at false lets other plugins handle the chat.)
  set_local_format: true
  # If you do not want MultiChat2 to handle any of the local chat messages, you can set this to true.
  # The message will still be sent to the proxy, unless prevent_global is set to true.
  prevent_local: false
  # The format of local messages.
  # The same placeholders as for the global format are possible here.
  # The message will be added at the end of the format.
  local_format: "&3[&bL&3] &f%displayname%&f: &7"

############################################################
# +------------------------------------------------------+ #
# |                   Channel Control                    | #
# +------------------------------------------------------+ #
############################################################

# This section allows you to force messages matching a specific format into a certain channel.
# For example, if you had a Towny town channel in the format: [TC],
# you could tell MultiChat to keep this local, even if the player is in global mode.
# This allows MultiChat to support Towny and other plugins without having to depend on them directly.

# Use regular expressions (regex) to match the channel format.
# Allowed channels are currently: local, global or current (for the player's currently selected channel).
# If ignore_format_code=true then format codes (&3 etc.) used in the chat format are filtered out before checking.

# The order matters, top has highest priority.
# Credit to metzg for many of these examples.

force_channel:
  # Example to make Towny's town channel stay local
  # This is the ID of the force_channel setting. It really doesn't matter what you put here.
  towny:
    # The regex that needs to apply to the chat message.
    regex: '^&f[[]&3TC&f].*'
    # If format codes should be ignored when applying the regex.
    ignore_format_codes: false
    # Where the message should be sent to.
    channel: 'local'

  # Example to make Towny's nation channel stay local
  towny_nation_channel:
    regex: '^&f[[]&6NC&f].*'
    ignore_format_codes: false
    channel: 'local'

  # Example to make Towny's admin channel stay local
  towny_admin_channel:
    regex: '^&f[[]&4ADMIN&f].*'
    ignore_format_codes: false
    channel: 'local'

  # Example to make Towny's mod channel stay local
  towny_mod_channel:
    regex: '^&f[[]&9MOD&f].*'
    ignore_format_codes: false
    channel: 'local'

  # Make Essentials local (range) chat stay local
  #essentials_local_channel:
  #  regex: '^[[]L].*'
  #  ignore_format_codes: true
  #  channel: 'local'

  # Make Essentials SHOUT go global
  #essentials_shout_channel:
  #  regex: '^[[]Shout].*'
  #  ignore_format_codes: true
  #  channel: 'global'

  # Some other plugin
  #think_action:
  #  regex: '^(.+) thinks: (.+)'
  #  ignore_format_codes: true
  #  channel: 'current' # current is useful because we can stop processing other regexes here, instead of waiting until the end and defaulting

  #slap_action:
  #  regex: '^(.+) slaps (.+) with a trout'
  #  ignore_format_codes: true
  #  channel: 'local'

  #slap_global_action:
  #  regex: '^(.+) slaps (.+) loudly with a trout'
  #  ignore_format_codes: true
  #  channel: 'global'
